version: '3'
services: 
    remora:
        build: .
        restart: always
        ports:
            - 80:80
        environment:
            - SERVER_ADDRESS=0.0.0.0
            - SERVER_PORT=80
            - SERVER_TIMEZONE=Asia/Jakarta
            - APP_NAME=remora
            - SWAGGER_SERVER_ADDRESS=http://0.0.0.0
            - PLAYBOOK_PATH=playbook
        command: /usr/bin/main -e production

  